version: "3.9"
services:
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./xcloner-backup-and-restore:/var/www/html/wp-content/plugins/xcloner-backup-and-restore:ro
    # To avoid conflicts, define your own port binding in docker-compose.override.yml. E.g.
    #services:
    #  wordpress:
    #    ports:
    #      - '8080:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  db:
    image: mariadb:10.5.8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    healthcheck:
      test: "/usr/bin/mysql --user=wordpress --password=wordpress --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 10

volumes:
  db_data: {}
