name: xcloner-testing

services:
  wordpress:
    depends_on:
      - db
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./xcloner-backup-and-restore:/src/xcloner-backup-and-restore:ro
    ports:
      - "${WORDPRESS_PORT:-8080}:80"
    environment:
      WORDPRESS_DEBUG: "${WORDPRESS_DEBUG:-false}"
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST:-db}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER:-wordpress}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD:-wordpress}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME:-wordpress}"
      WORDPRESS_URL: "${WORDPRESS_URL:-http://localhost:8080}"
      WORDPRESS_TITLE: "${WORDPRESS_TITLE:-WordPress}"
      WORDPRESS_ADMIN_USER: "${WORDPRESS_ADMIN_USER:-admin}"
      WORDPRESS_ADMIN_PASSWORD: "${WORDPRESS_ADMIN_PASSWORD:-password}"
      WORDPRESS_ADMIN_EMAIL: "${WORDPRESS_ADMIN_EMAIL:-example@example.com}"
      XCLONER_GDRIVE_CLIENT_ID: "${XCLONER_GDRIVE_CLIENT_ID:-}"
      XCLONER_GDRIVE_REDIRECT_URL: "${XCLONER_GDRIVE_REDIRECT_URL:-}"

  db:
    image: mariadb:10.5.8
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${WORDPRESS_DB_PASSWORD:-wordpress}"
      MYSQL_DATABASE: "${WORDPRESS_DB_NAME:-wordpress}"
      MYSQL_USER: "${WORDPRESS_DB_USER:-wordpress}"
      MYSQL_PASSWORD: "${WORDPRESS_DB_PASSWORD:-wordpress}"
    healthcheck:
      test: "/usr/bin/mysql --user=wordpress --password=wordpress --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 10

volumes:
  db_data: {}
