name: xcloner-testing
services:
  wordpress:
    depends_on:
      - db
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./xcloner-backup-and-restore:/src/xcloner-backup-and-restore:ro
    # To avoid conflicts, define your own port binding in docker-compose.override.yml. E.g.
    #services:
    #  wordpress:
    #    ports:
    #      - '8080:80'
    environment:
      WORDPRESS_DEBUG: true
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_URL: https://wordpress.xcloner.local
      WORDPRESS_TITLE: XCloner Testing
      WORDPRESS_ADMIN_USER: admin
      WORDPRESS_ADMIN_PASSWORD: admin
      WORDPRESS_ADMIN_EMAIL: hello@watchful.net

  db:
    image: mariadb:10.5.8
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    healthcheck:
      test: "/usr/bin/mysql --user=wordpress --password=wordpress --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 10

volumes:
  db_data: {}
