name: Deploy to WordPress.org
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.3'
        tools: composer
      run: ${{ github.workspace }}/.github/workflows/deploy-wp.sh
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}